In [1]:
# Import dependencies
import pandas as pd
import gmaps
import requests

#import API key
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Sinnamary,5.3833,-52.9500,77.65,89,86,10.63,GF,2022-05-20 20:32:57
1,1,Atuona,-9.8000,-139.0333,77.38,67,0,9.75,PF,2022-05-20 20:32:57
2,2,Pisco,-13.7000,-76.2167,71.65,60,0,11.50,PE,2022-05-20 20:32:58
3,3,Touros,-5.1989,-35.4608,79.18,81,81,7.61,BR,2022-05-20 20:32:58
4,4,Ajdabiya,30.7554,20.2263,66.22,39,0,13.27,LY,2022-05-20 20:32:59

In [3]:
#Get data types
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

# Create a Maximum Termperature Heatmap

In [9]:
# Configure gmaps to use your Google API key
gmaps.configure(api_key=g_key)

In [10]:
# Heatmap of temperature
# 1 Assign locations to array of latitude and longitude pairs
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some variables
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp,0))

# 3. Assign the figure variable to the gmaps.figure() attribue.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level = 1.5)

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp])

# 5. Add teh heatmap layer.
fig.add_layer(heat_layer)

# 6. Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind_speed = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind_speed, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

## Feature that allows customers to search for locations they want to travel based on temperature preferences

In [15]:
# Ask the customer to add a minimum and maximum temperature value
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [16]:
# Filter the dataset to find the cities that fit the criteria
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                      (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Sinnamary,5.3833,-52.9500,77.65,89,86,10.63,GF,2022-05-20 20:32:57
1,1,Atuona,-9.8000,-139.0333,77.38,67,0,9.75,PF,2022-05-20 20:32:57
3,3,Touros,-5.1989,-35.4608,79.18,81,81,7.61,BR,2022-05-20 20:32:58
5,5,Puerto Ayora,-0.7393,-90.3518,80.56,91,53,1.99,EC,2022-05-20 20:32:59
12,12,Port Blair,11.6667,92.7500,83.07,79,100,18.45,IN,2022-05-20 20:33:02
...,...,...,...,...,...,...,...,...,...,...
553,553,Vanimo,-2.6741,141.3028,77.49,90,48,3.94,PG,2022-05-20 20:48:33
557,557,Palu,-0.8917,119.8707,76.17,95,100,1.95,ID,2022-05-20 20:48:35
566,566,Yarada,17.6500,83.2667,86.32,74,40,11.50,IN,2022-05-20 20:49:39
568,568,Lahaina,20.8783,-156.6825,84.20,78,62,2.82,US,2022-05-20 20:49:40
571,571,Tabou,4.4230,-7.3528,77.86,87,100,11.86,CI,2022-05-20 20:49:42

In [17]:
# Determine if there are null values
preferred_cities_df.count()

City_ID       159
City          159
Lat           159
Lng           159
Max Temp      159
Humidity      159
Cloudiness    159
Wind Speed    159
Country       159
Date          159
dtype: int64

## Get Travel Destinations

In [18]:
# Create a datafram called hotel_df to store hotel_names along with city, country, max_temp, and coordinates
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head()

            City Country  Max Temp      Lat       Lng Hotel Name
0      Sinnamary      GF     77.65   5.3833  -52.9500
1         Atuona      PF     77.38  -9.8000 -139.0333
3         Touros      BR     79.18  -5.1989  -35.4608
5   Puerto Ayora      EC     80.56  -0.7393  -90.3518
12    Port Blair      IN     83.07  11.6667   92.7500

In [20]:
# Set parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

### Iterate through hotel_df dataframe

In [22]:
# Iterate through dataframe
for index, row in hotel_df.iterrows():
    # Get latitude and longitude
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Use search term: "lodging" and our latitude and longitude
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get JSON data from search
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from results and store name
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

ConnectionError: HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/place/nearbysearch/json?radius=5000&type=lodging&key=AIzaSyAmacnVnoxsDnQF04VBzUKQ6aBx8Gz4lYM&location=10.2104%2C-83.6807 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000012C8F439688>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

In [24]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Sinnamary,GF,77.65,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
1,Atuona,PF,77.38,-9.8000,-139.0333,Villa Enata
3,Touros,BR,79.18,-5.1989,-35.4608,INN NEW HORIZON
5,Puerto Ayora,EC,80.56,-0.7393,-90.3518,Finch Bay Galapagos Hotel
12,Port Blair,IN,83.07,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
...,...,...,...,...,...,...
553,Vanimo,PG,77.49,-2.6741,141.3028,
557,Palu,ID,76.17,-0.8917,119.8707,
566,Yarada,IN,86.32,17.6500,83.2667,
568,Lahaina,US,84.20,20.8783,-156.6825,
571,Tabou,CI,77.86,4.4230,-7.3528,

In [30]:
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</d1>
"""

# Store the dataframe row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [31]:
# Add a heatmap of temperature for vacation spots and marker for each city
locations = hotel_df[["Lat","Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0,31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,weights=max_temp, dissipating=False,
                                max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

fig

Figure(layout=FigureLayout(height='420px'))